# Generated by Django 5.2 on 2025-04-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
